# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0002_document_image_person_sound_video_vimeo'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=160)),
                ('description', tinymce.models.HTMLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hosted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(default=b'#000000', max_length=22)),
                ('do_color_inverse', models.BooleanField(default=True)),
                ('do_get_guests', models.BooleanField(default=False)),
                ('do_show_guests', models.BooleanField(default=False)),
                ('do_show_proposals', models.BooleanField(default=False)),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('affiliation', models.CharField(blank=True, help_text=b'Are you in a group or organization that you think will interest others? (optional)', max_length=160, null=True, verbose_name=b'Group or organization')),
                ('proposal', models.TextField(blank=True, help_text=b'What would you like to talk about or work on in this event? (optional)', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('attending_status', models.CharField(choices=[(b'yes', b'Yes'), (b'no', b'No'), (b'maybe', b'Maybe'), (b'no_rsvp', b"Hasn't RSVPed yet")], default=b'no_rsvp', max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, through='events.Guest', to='basic.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='_event_related_events_+', to='events.Event'),
        ),
    ]
