# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20170116_2041'),
        ('basic', '0002_document_image_person_sound_video_vimeo'),
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=160)),
                ('body', tinymce.models.HTMLField()),
                ('date_published', models.DateTimeField()),
                ('color', models.CharField(default=b'#000000', max_length=22)),
                ('do_color_inverse', models.BooleanField(default=True)),
                ('do_get_signatures', models.BooleanField(default=False)),
                ('do_show_signatures', models.BooleanField(default=False)),
                ('related_events', models.ManyToManyField(blank=True, to='events.Event')),
                ('related_letters', models.ManyToManyField(blank=True, related_name='_letter_related_letters_+', to='letters.Letter')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.Letter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='signatures',
            field=models.ManyToManyField(blank=True, through='letters.Signature', to='basic.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together=set([('person', 'letter')]),
        ),
    ]
