# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('media', models.FileField(max_length=200, upload_to=b'documents/', verbose_name=b'PDF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('media', models.FileField(max_length=200, upload_to=b'images/', verbose_name=b'Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('media', models.FileField(max_length=200, upload_to=b'sounds/', verbose_name=b'Audio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('media', models.FileField(max_length=200, upload_to=b'video/', verbose_name=b'Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vimeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('media', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
