# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=140)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=160)),
                ('position', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
